// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks_internal

import io "io"
import mock "github.com/stretchr/testify/mock"

// Request is an autogenerated mock type for the Request type
type Request struct {
	mock.Mock
}

// File provides a mock function with given fields: fieldname, filename, r
func (_m *Request) File(fieldname string, filename string, r io.Reader) {
	_m.Called(fieldname, filename, r)
}

// Var provides a mock function with given fields: key, value
func (_m *Request) Var(key string, value interface{}) {
	_m.Called(key, value)
}
