// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import io "io"
import mock "github.com/stretchr/testify/mock"

// Cacher is an autogenerated mock type for the Cacher type
type Cacher struct {
	mock.Mock
}

// Cache provides a mock function with given fields: ctx, r, dest, mimeType
func (_m *Cacher) Cache(ctx context.Context, r io.Reader, dest string, mimeType string) (string, error) {
	ret := _m.Called(ctx, r, dest, mimeType)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string, string) string); ok {
		r0 = rf(ctx, r, dest, mimeType)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, io.Reader, string, string) error); ok {
		r1 = rf(ctx, r, dest, mimeType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
