// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import streamio "github.com/veritone/edge-stream-ingestor/streamio"

// Streamer is an autogenerated mock type for the Streamer type
type Streamer struct {
	mock.Mock
}

// Stream provides a mock function with given fields: ctx
func (_m *Streamer) Stream(ctx context.Context) *streamio.Stream {
	ret := _m.Called(ctx)

	var r0 *streamio.Stream
	if rf, ok := ret.Get(0).(func(context.Context) *streamio.Stream); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*streamio.Stream)
		}
	}

	return r0
}
