// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import streamio "github.com/veritone/edge-stream-ingestor/streamio"

// StreamWriter is an autogenerated mock type for the StreamWriter type
type StreamWriter struct {
	mock.Mock
}

// BytesWritten provides a mock function with given fields:
func (_m *StreamWriter) BytesWritten() int64 {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// WriteStream provides a mock function with given fields: _a0, _a1
func (_m *StreamWriter) WriteStream(_a0 context.Context, _a1 *streamio.Stream) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *streamio.Stream) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
